name: Realty Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_SERVICE: ${{ secrets.TELEGRAM_SERVICE }}
      SS_BASE_URL: ${{ secrets.SS_BASE_URL }}
      SS_LISTINGS_URL: ${{ secrets.SS_LISTINGS_URL }}
      UNWANTED_DISTRICTS: ${{ secrets.UNWANTED_DISTRICTS }}
      LISTING_MIN_PRICE: ${{ secrets.LISTING_MIN_PRICE }}
      LISTING_MAX_PRICE: ${{ secrets.LISTING_MAX_PRICE }}
    steps:
      - uses: actions/checkout@v3

      - name: Ensure scraped links file exists
        run: |
          mkdir -p ./data
          touch ./data/scraped_links.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python Realty.py

      - name: Commit scraped links if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/scraped_links.txt
          if ! git diff --cached --quiet; then
            git commit -m "Update scraped links [skip ci]"
            git push
          else
            echo "No changes in scraped links, skipping commit."
          fi
