name: Realty Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_SERVICE_IMPL: ${{ vars.TELEGRAM_SERVICE_IMPL }}
      SS_BASE_URL: ${{ vars.SS_BASE_URL }}
      SS_LISTINGS_URL: ${{ vars.SS_LISTINGS_URL }}
      UNWANTED_DISTRICTS: ${{ vars.UNWANTED_DISTRICTS }}
      LISTING_MIN_PRICE: ${{ vars.LISTING_MIN_PRICE }}
      LISTING_MAX_PRICE: ${{ vars.LISTING_MAX_PRICE }}
      LISTING_MIN_SIZE: ${{ vars.LISTING_MIN_SIZE }}
      LISTING_MAX_SIZE: ${{ vars.LISTING_MAX_SIZE }}
      LISTING_MIN_ROOMS: ${{ vars.LISTING_MIN_ROOMS }}
      LISTING_MAX_ROOMS: ${{ vars.LISTING_MAX_ROOMS }}
      LISTING_MIN_PRICE_PER_M2: ${{ vars.LISTING_MIN_PRICE_PER_M2 }}
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      GCS_SERVICE_IMPL: ${{ vars.GCS_SERVICE_IMPL }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python src/Realty.py